"""Static sector classifications.

Yahoo's `.info` endpoint — the only source of sector data in yfinance — is
blocked or heavily throttled from datacenter IPs, so it returns nothing in
production even though it works from a residential connection. Sector
classification is stable (a company changes sector once in a decade, if ever),
so a static map is a reasonable source of truth here; `.info` is consulted only
to fill in symbols this map does not cover.

Names match Yahoo's own sector vocabulary so both sources agree.
"""

SECTORS: dict[str, str] = {
    # Broad-market and asset-class ETFs
    "SPY": "Fund / Index",
    "VOO": "Fund / Index",
    "IVV": "Fund / Index",
    "VTI": "Fund / Index",
    "QQQ": "Fund / Index",
    "DIA": "Fund / Index",
    "IWM": "Fund / Index",
    "VEA": "Fund / Index",
    "VWO": "Fund / Index",
    "EFA": "Fund / Index",
    "AGG": "Bonds",
    "BND": "Bonds",
    "TLT": "Bonds",
    "IEF": "Bonds",
    "SHY": "Bonds",
    "LQD": "Bonds",
    "HYG": "Bonds",
    "GLD": "Commodities",
    "SLV": "Commodities",
    "USO": "Commodities",
    "DBC": "Commodities",
    "VNQ": "Real Estate",
    "^GSPC": "Fund / Index",
    "^DJI": "Fund / Index",
    "^IXIC": "Fund / Index",
    # Technology
    "AAPL": "Technology",
    "MSFT": "Technology",
    "NVDA": "Technology",
    "AVGO": "Technology",
    "ORCL": "Technology",
    "CRM": "Technology",
    "ADBE": "Technology",
    "AMD": "Technology",
    "INTC": "Technology",
    "CSCO": "Technology",
    "IBM": "Technology",
    "QCOM": "Technology",
    "TXN": "Technology",
    "NOW": "Technology",
    "PLTR": "Technology",
    "SMCI": "Technology",
    "MU": "Technology",
    # Communication Services
    "GOOGL": "Communication Services",
    "GOOG": "Communication Services",
    "META": "Communication Services",
    "NFLX": "Communication Services",
    "DIS": "Communication Services",
    "T": "Communication Services",
    "VZ": "Communication Services",
    "TMUS": "Communication Services",
    # Consumer Cyclical
    "AMZN": "Consumer Cyclical",
    "TSLA": "Consumer Cyclical",
    "HD": "Consumer Cyclical",
    "MCD": "Consumer Cyclical",
    "NKE": "Consumer Cyclical",
    "SBUX": "Consumer Cyclical",
    "LOW": "Consumer Cyclical",
    "BKNG": "Consumer Cyclical",
    "F": "Consumer Cyclical",
    "GM": "Consumer Cyclical",
    # Consumer Defensive
    "KO": "Consumer Defensive",
    "PEP": "Consumer Defensive",
    "PG": "Consumer Defensive",
    "WMT": "Consumer Defensive",
    "COST": "Consumer Defensive",
    "PM": "Consumer Defensive",
    "MO": "Consumer Defensive",
    "MDLZ": "Consumer Defensive",
    "CL": "Consumer Defensive",
    "TGT": "Consumer Defensive",
    # Healthcare
    "JNJ": "Healthcare",
    "UNH": "Healthcare",
    "LLY": "Healthcare",
    "PFE": "Healthcare",
    "MRK": "Healthcare",
    "ABBV": "Healthcare",
    "TMO": "Healthcare",
    "ABT": "Healthcare",
    "DHR": "Healthcare",
    "BMY": "Healthcare",
    "AMGN": "Healthcare",
    "CVS": "Healthcare",
    # Financial Services
    "JPM": "Financial Services",
    "BAC": "Financial Services",
    "WFC": "Financial Services",
    "GS": "Financial Services",
    "MS": "Financial Services",
    "C": "Financial Services",
    "BRK-B": "Financial Services",
    "V": "Financial Services",
    "MA": "Financial Services",
    "AXP": "Financial Services",
    "SCHW": "Financial Services",
    "BLK": "Financial Services",
    "SPGI": "Financial Services",
    # Energy
    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "SLB": "Energy",
    "EOG": "Energy",
    "PSX": "Energy",
    "MPC": "Energy",
    # Industrials
    "BA": "Industrials",
    "CAT": "Industrials",
    "HON": "Industrials",
    "GE": "Industrials",
    "UPS": "Industrials",
    "UNP": "Industrials",
    "RTX": "Industrials",
    "LMT": "Industrials",
    "DE": "Industrials",
    # Utilities / Materials / Real Estate
    "NEE": "Utilities",
    "DUK": "Utilities",
    "SO": "Utilities",
    "LIN": "Basic Materials",
    "SHW": "Basic Materials",
    "FCX": "Basic Materials",
    "AMT": "Real Estate",
    "PLD": "Real Estate",
    # Crypto
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
}


def lookup(ticker: str) -> str | None:
    return SECTORS.get(ticker.upper())
